project:
  type: website
  output-dir: docs

website:
  title: "Jack Royle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: research.qmd
        text: Conference submissions        
      - href: CV.qmd
        text: CV

format:
  html:
    theme: cosmo
    toc: false




